-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
-- Revisado e otimizado para Oracle Database 21c
-- Data da revisão: 2025-09-11

-- =============================================
-- CRIAÇÃO DAS TABELAS
-- =============================================

CREATE TABLE categoria_produtos (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao    VARCHAR2(50 CHAR) NOT NULL,
    data_criacao DATE DEFAULT SYSDATE NOT NULL
);
ALTER TABLE categoria_produtos ADD CONSTRAINT PK_categoria_produtos PRIMARY KEY (id_categoria);

CREATE TABLE produtos (
    id_produto          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_produto        VARCHAR2(50 CHAR) NOT NULL,
    descricao           VARCHAR2(250 CHAR),
    marca               VARCHAR2(50 CHAR),
    gestao              VARCHAR2(50 CHAR) NOT NULL,
    id_categoria_produto INTEGER NOT NULL -- Relação corrigida
);
ALTER TABLE produtos ADD CONSTRAINT PK_produtos PRIMARY KEY (id_produto);

CREATE TABLE clientes (
    id_cliente       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_completo    VARCHAR2(100 CHAR) NOT NULL,
    tipo_cliente     VARCHAR2(2 CHAR) NOT NULL, -- 'PF' ou 'PJ'
    cpf              VARCHAR2(11 CHAR) UNIQUE,
    cnpj             VARCHAR2(14 CHAR) UNIQUE,
    razao_social     VARCHAR2(115 CHAR),
    nome_fantasia    VARCHAR2(115 CHAR),
    telefone         VARCHAR2(15 CHAR) NOT NULL,
    e_mail           VARCHAR2(100 CHAR) NOT NULL UNIQUE,
    endereco         VARCHAR2(100 CHAR),
    cidade           VARCHAR2(100 CHAR),
    uf               VARCHAR2(2 CHAR),
    cep              VARCHAR2(8 CHAR),
    data_cadastro    DATE DEFAULT SYSDATE NOT NULL,
    data_atualizacao DATE,
    CONSTRAINT CHK_tipo_cliente CHECK (tipo_cliente IN ('PF', 'PJ')),
    CONSTRAINT CHK_cliente_documento CHECK (
        (tipo_cliente = 'PF' AND cpf IS NOT NULL AND cnpj IS NULL) OR
        (tipo_cliente = 'PJ' AND cnpj IS NOT NULL AND cpf IS NULL)
    )
);
ALTER TABLE clientes ADD CONSTRAINT PK_clientes PRIMARY KEY (id_cliente);

CREATE TABLE fornecedor (
    id_fornecedor     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cnpj              VARCHAR2(14 CHAR) NOT NULL UNIQUE,
    razao_social      VARCHAR2(100 CHAR) NOT NULL,
    nome_fantasia     VARCHAR2(100 CHAR),
    cnae_principal    VARCHAR2(7 CHAR),
    natureza_juridica VARCHAR2(4 CHAR),
    endereco          VARCHAR2(200 CHAR),
    cep               VARCHAR2(8 CHAR),
    uf                VARCHAR2(2 CHAR),
    email             VARCHAR2(100 CHAR),
    telefone          VARCHAR2(15 CHAR),
    whatsapp          VARCHAR2(15 CHAR),
    data_atualizacao  DATE
);
ALTER TABLE fornecedor ADD CONSTRAINT PK_fornecedor PRIMARY KEY (id_fornecedor);

CREATE TABLE compras (
    id_compra            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_compra          DATE DEFAULT SYSDATE NOT NULL,
    chave_acesso_nfe     VARCHAR2(44 CHAR) UNIQUE,
    valor_total          NUMBER(10, 2) NOT NULL,
    nota_fiscal          VARCHAR2(20 CHAR),
    status               VARCHAR2(30 CHAR) NOT NULL,
    ncm                  VARCHAR2(8 CHAR),
    cest_cst             VARCHAR2(7 CHAR),
    icms                 NUMBER(10, 2),
    pis                  NUMBER(10, 2),
    icms_st              NUMBER(10, 2),
    diferencial_aliquota NUMBER(10, 2),
    id_fornecedor        INTEGER NOT NULL
);
ALTER TABLE compras ADD CONSTRAINT PK_compras PRIMARY KEY (id_compra);

CREATE TABLE variacao_produtos (
    id_variacao       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tamanho           VARCHAR2(10 CHAR),
    cor               VARCHAR2(20 CHAR),
    ean               VARCHAR2(13 CHAR) UNIQUE,
    sku               VARCHAR2(20 CHAR) NOT NULL UNIQUE,
    custo             NUMBER(10, 2) NOT NULL,
    preco_venda       NUMBER(10, 2) NOT NULL,
    estoque_atual     INTEGER DEFAULT 0 NOT NULL,
    margem            NUMBER(5, 2),
    id_produto        INTEGER NOT NULL,
    id_fornecedor     INTEGER
);
ALTER TABLE variacao_produtos ADD CONSTRAINT PK_variacao_produtos PRIMARY KEY (id_variacao);

CREATE TABLE estoque (
    id_estoque    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantidade    INTEGER NOT NULL,
    data_atualizacao DATE DEFAULT SYSDATE,
    id_variacao   INTEGER NOT NULL
);
ALTER TABLE estoque ADD CONSTRAINT PK_estoque PRIMARY KEY (id_estoque);

CREATE TABLE movimento_estoque (
    id_movimento         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_movimento       VARCHAR2(100 CHAR) NOT NULL, -- 'ENTRADA', 'SAIDA', 'AJUSTE'
    quantidade           INTEGER NOT NULL,
    data_movimento       DATE DEFAULT SYSDATE NOT NULL,
    referencia_movimento INTEGER, -- ID da Venda ou Compra
    id_fornecedor        INTEGER, -- Opcional, para entradas
    id_variacao          INTEGER NOT NULL
);
ALTER TABLE movimento_estoque ADD CONSTRAINT PK_movimento_estoque PRIMARY KEY (id_movimento);

CREATE TABLE usuarios (
    id_usuario     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome           VARCHAR2(150 CHAR) NOT NULL,
    email          VARCHAR2(100 CHAR) NOT NULL UNIQUE,
    funcao         VARCHAR2(20 CHAR) NOT NULL,
    status_usuario VARCHAR2(15 CHAR) NOT NULL,
    data_criacao   DATE DEFAULT SYSDATE NOT NULL,
    data_status    DATE,
    ultimo_login   DATE
);
ALTER TABLE usuarios ADD CONSTRAINT PK_usuarios PRIMARY KEY (id_usuario);

CREATE TABLE vendas (
    id_venda            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_venda          DATE DEFAULT SYSDATE NOT NULL,
    valor_total         NUMBER(10, 2) NOT NULL,
    status              VARCHAR2(15 CHAR) NOT NULL,
    id_cliente          INTEGER NOT NULL,
    id_usuario          INTEGER NOT NULL
);
ALTER TABLE vendas ADD CONSTRAINT PK_vendas PRIMARY KEY (id_venda);

CREATE TABLE itens_venda (
    id_item_venda   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantidade      INTEGER NOT NULL,
    preco_unitario  NUMBER(10, 2) NOT NULL,
    subtotal        NUMBER(10, 2) NOT NULL,
    desconto        NUMBER(10, 2) DEFAULT 0,
    id_venda        INTEGER NOT NULL,
    id_variacao     INTEGER NOT NULL
);
ALTER TABLE itens_venda ADD CONSTRAINT PK_itens_venda PRIMARY KEY (id_item_venda);

CREATE TABLE itens_compra (
    id_item_compra   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantidade       INTEGER NOT NULL,
    custo_unitario   NUMBER(10, 2) NOT NULL,
    valor_total_item NUMBER(10, 2) NOT NULL,
    cfop             VARCHAR2(4 CHAR),
    ncm              VARCHAR2(8 CHAR),
    cest_cst         VARCHAR2(7 CHAR),
    id_compra        INTEGER NOT NULL,
    id_variacao      INTEGER NOT NULL
);
ALTER TABLE itens_compra ADD CONSTRAINT PK_itens_compra PRIMARY KEY (id_item_compra);

CREATE TABLE contas_a_pagar (
    id_cta_a_pgto   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    num_parcelas    INTEGER NOT NULL,
    data_emissao    DATE NOT NULL,
    data_vencimento DATE NOT NULL,
    valor_original  NUMBER(10, 2) NOT NULL,
    valor_pago      NUMBER(10, 2) DEFAULT 0,
    saldo_devedor   NUMBER(10, 2) NOT NULL,
    status_conta    VARCHAR2(30 CHAR) NOT NULL,
    id_compra       INTEGER NOT NULL,
    id_fornecedor   INTEGER NOT NULL
);
ALTER TABLE contas_a_pagar ADD CONSTRAINT PK_contas_a_pagar PRIMARY KEY (id_cta_a_pgto);

CREATE TABLE contas_a_receber (
    id_cta_a_receber    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    numero_parcela      INTEGER NOT NULL,
    data_emissao        DATE NOT NULL,
    data_vencimento     DATE NOT NULL,
    valor_original      NUMBER(10, 2) NOT NULL,
    valor_pago          NUMBER(10, 2) DEFAULT 0,
    saldo_devedor       NUMBER(10, 2) NOT NULL,
    status_conta        VARCHAR2(15 CHAR) NOT NULL,
    id_venda            INTEGER NOT NULL,
    id_cliente          INTEGER NOT NULL
);
ALTER TABLE contas_a_receber ADD CONSTRAINT PK_contas_a_receber PRIMARY KEY (id_cta_a_receber);

CREATE TABLE formas_pagamentos (
    id_forma_pgto INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao     VARCHAR2(150 CHAR) NOT NULL UNIQUE
);
ALTER TABLE formas_pagamentos ADD CONSTRAINT PK_formas_pagamentos PRIMARY KEY (id_forma_pgto);

CREATE TABLE pagamentos (
    id_pagamento    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_pagamento  DATE NOT NULL,
    valor_pagamento NUMBER(10, 2) NOT NULL,
    valor_juros     NUMBER(10, 2) DEFAULT 0,
    valor_desconto  NUMBER(10, 2) DEFAULT 0,
    id_forma_pgto   INTEGER NOT NULL,
    id_cta_a_pgto   INTEGER NOT NULL
);
ALTER TABLE pagamentos ADD CONSTRAINT PK_pagamentos PRIMARY KEY (id_pagamento);

CREATE TABLE recebimentos (
    id_recebimento      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_pagamento      DATE NOT NULL,
    valor_pagamento     NUMBER(10, 2) NOT NULL,
    valor_juros         NUMBER(10, 2) DEFAULT 0,
    valor_desconto      NUMBER(10, 2) DEFAULT 0,
    valor_tx_maquininha NUMBER(10, 2) DEFAULT 0,
    valor_liquido       NUMBER(10, 2) NOT NULL,
    id_cta_a_receber    INTEGER NOT NULL,
    id_forma_pgto       INTEGER NOT NULL
);
ALTER TABLE recebimentos ADD CONSTRAINT PK_recebimentos PRIMARY KEY (id_recebimento);

CREATE TABLE condicao_pagamento (
    id_condicao         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao           VARCHAR2(50 CHAR) NOT NULL,
    parcelas            INTEGER NOT NULL,
    intervalo_dias_parc INTEGER NOT NULL
);
ALTER TABLE condicao_pagamento ADD CONSTRAINT PK_condicao_pagamento PRIMARY KEY (id_condicao);

CREATE TABLE maquininhas (
    id_maquininha        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_maquininha      VARCHAR2(50 CHAR) NOT NULL, -- Corrigido para VARCHAR2
    taxa_credito_a_vista NUMBER(5, 2) NOT NULL, -- Corrigido precisão
    taxa_debito          NUMBER(5, 2) NOT NULL -- Corrigido precisão
);
ALTER TABLE maquininhas ADD CONSTRAINT PK_maquininhas PRIMARY KEY (id_maquininha);

CREATE TABLE taxa_parcelamento (
    id_taxa         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    numero_parcelas INTEGER NOT NULL,
    taxa            NUMBER(5, 2) NOT NULL, -- Corrigido precisão
    id_maquininha   INTEGER NOT NULL
);
ALTER TABLE taxa_parcelamento ADD CONSTRAINT PK_taxa_parcelamento PRIMARY KEY (id_taxa);

CREATE TABLE empresa (
    id_empresa        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cnpj              VARCHAR2(14 CHAR) NOT NULL UNIQUE,
    razao_social      VARCHAR2(100 CHAR) NOT NULL,
    nome_fantasia     VARCHAR2(100 CHAR),
    cnae_principal    VARCHAR2(7 CHAR),
    natureza_juridica VARCHAR2(4 CHAR),
    endereco          VARCHAR2(200 CHAR),
    cep               VARCHAR2(8 CHAR),
    uf                VARCHAR2(2 CHAR),
    email             VARCHAR2(100 CHAR),
    telefone          VARCHAR2(15 CHAR),
    whatsapp          VARCHAR2(15 CHAR),
    data_atualizacao  DATE -- Corrigido para DATE
);
ALTER TABLE empresa ADD CONSTRAINT PK_empresa PRIMARY KEY (id_empresa);


-- =============================================
-- DEFINIÇÃO DAS CHAVES ESTRANGEIRAS (FOREIGN KEYS)
-- =============================================

-- Tabela: produtos
ALTER TABLE produtos ADD CONSTRAINT FK_produtos_categoria FOREIGN KEY (id_categoria_produto) REFERENCES categoria_produtos (id_categoria);

-- Tabela: compras
ALTER TABLE compras ADD CONSTRAINT FK_compras_fornecedor FOREIGN KEY (id_fornecedor) REFERENCES fornecedor (id_fornecedor);

-- Tabela: variacao_produtos
ALTER TABLE variacao_produtos ADD CONSTRAINT FK_var_prod_produtos FOREIGN KEY (id_produto) REFERENCES produtos (id_produto);
ALTER TABLE variacao_produtos ADD CONSTRAINT FK_var_prod_fornecedor FOREIGN KEY (id_fornecedor) REFERENCES fornecedor (id_fornecedor);

-- Tabela: estoque
ALTER TABLE estoque ADD CONSTRAINT FK_estoque_var_prod FOREIGN KEY (id_variacao) REFERENCES variacao_produtos (id_variacao);

-- Tabela: movimento_estoque
ALTER TABLE movimento_estoque ADD CONSTRAINT FK_mov_est_var_prod FOREIGN KEY (id_variacao) REFERENCES variacao_produtos (id_variacao);
ALTER TABLE movimento_estoque ADD CONSTRAINT FK_mov_est_fornecedor FOREIGN KEY (id_fornecedor) REFERENCES fornecedor (id_fornecedor);

-- Tabela: vendas
ALTER TABLE vendas ADD CONSTRAINT FK_vendas_clientes FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente);
ALTER TABLE vendas ADD CONSTRAINT FK_vendas_usuarios FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

-- Tabela: itens_venda
ALTER TABLE itens_venda ADD CONSTRAINT FK_itens_venda_vendas FOREIGN KEY (id_venda) REFERENCES vendas (id_venda);
ALTER TABLE itens_venda ADD CONSTRAINT FK_itens_venda_var_prod FOREIGN KEY (id_variacao) REFERENCES variacao_produtos (id_variacao);

-- Tabela: itens_compra
ALTER TABLE itens_compra ADD CONSTRAINT FK_itens_compra_compras FOREIGN KEY (id_compra) REFERENCES compras (id_compra);
ALTER TABLE itens_compra ADD CONSTRAINT FK_itens_compra_var_prod FOREIGN KEY (id_variacao) REFERENCES variacao_produtos (id_variacao);

-- Tabela: contas_a_pagar
ALTER TABLE contas_a_pagar ADD CONSTRAINT FK_ct_pagar_compras FOREIGN KEY (id_compra) REFERENCES compras (id_compra);
ALTER TABLE contas_a_pagar ADD CONSTRAINT FK_ct_pagar_fornecedor FOREIGN KEY (id_fornecedor) REFERENCES fornecedor (id_fornecedor);

-- Tabela: contas_a_receber
ALTER TABLE contas_a_receber ADD CONSTRAINT FK_ct_receber_vendas FOREIGN KEY (id_venda) REFERENCES vendas (id_venda);
ALTER TABLE contas_a_receber ADD CONSTRAINT FK_ct_receber_clientes FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente);

-- Tabela: pagamentos
ALTER TABLE pagamentos ADD CONSTRAINT FK_pagamentos_ct_pagar FOREIGN KEY (id_cta_a_pgto) REFERENCES contas_a_pagar (id_cta_a_pgto);
ALTER TABLE pagamentos ADD CONSTRAINT FK_pagamentos_formas_pgto FOREIGN KEY (id_forma_pgto) REFERENCES formas_pagamentos (id_forma_pgto);

-- Tabela: recebimentos
ALTER TABLE recebimentos ADD CONSTRAINT FK_recebimentos_ct_receber FOREIGN KEY (id_cta_a_receber) REFERENCES contas_a_receber (id_cta_a_receber);
ALTER TABLE recebimentos ADD CONSTRAINT FK_recebimentos_formas_pgto FOREIGN KEY (id_forma_pgto) REFERENCES formas_pagamentos (id_forma_pgto);

-- Tabela: taxa_parcelamento
ALTER TABLE taxa_parcelamento ADD CONSTRAINT FK_taxa_parc_maquininhas FOREIGN KEY (id_maquininha) REFERENCES maquininhas (id_maquininha);

-- =============================================
-- ALTERAÇÕES E MELHORIAS NAS TABELAS)
-- =============================================

-- Incluindo a coluna "status" nas tabelas abaixo. 

ALTER TABLE clientes
ADD status VARCHAR(15) DEFAULT 'Ativo' NOT NULL;

ALTER TABLE usuarios
ADD status VARCHAR(15) DEFAULT 'Ativo' NOT NULL;

ALTER TABLE produtos
ADD status VARCHAR(15) DEFAULT 'Ativo' NOT NULL;

ALTER TABLE variacao_produtos
ADD status VARCHAR(15) DEFAULT 'Ativo' NOT NULL;

ALTER TABLE fornecedor
ADD status VARCHAR(15) DEFAULT 'Ativo' NOT NULL;

ALTER TABLE categoria_produtos
ADD status VARCHAR(15) DEFAULT 'Ativo' NOT NULL;

ALTER TABLE formas_pagamentos
ADD status VARCHAR(15) DEFAULT 'Ativo' NOT NULL;

ALTER TABLE condicao_pagamento
ADD status VARCHAR(15) DEFAULT 'Ativo' NOT NULL;

ALTER TABLE maquininhas
ADD status VARCHAR(15) DEFAULT 'Ativo' NOT NULL;

-- Inclusão da coluna "data_atualizacao" na tabela "fornecedor":

ALTER TABLE fornecedor
ADD data_cadastro DATE NOT NULL;

ALTER TABLE fornecedor
MODIFY data_cadastro DEFAULT SYSDATE;


-- Inclusão automática de data de atualização nas tabelas abaixo:

CREATE OR REPLACE TRIGGER trg_clientes_data_atualizacao
BEFORE UPDATE ON clientes
FOR EACH ROW
BEGIN
    -- Define o valor da coluna 'data_atualizacao' da linha que está sendo alterada
    -- para a data e hora atuais do servidor do banco de dados.
    :new.data_atualizacao := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_forncedor_data_atualizacao
BEFORE UPDATE ON fornecedor
FOR EACH ROW
BEGIN
    -- Define o valor da coluna 'data_atualizacao' da linha que está sendo alterada
    -- para a data e hora atuais do servidor do banco de dados.
    :new.data_atualizacao := SYSDATE;
END;
/






