ALTER SESSION SET "_ORALCE_SCRIPT"=true;
CREATE USER closet IDENTIFIED BY "oracle";
GRANT ALL PRIVILEGES TO closet;
GRANT SYSDBA TO closet; 
GRANT CREATE SESSION TO closet; 
ALTER SESSION SET CURRENT_SCHEMA=closet;
